---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject2
  template:
    metadata:
      labels:
        app: myproject2
    spec:
      containers:
      - name: healthcare
        image: deepak377/myproject2:$BUILD_NUMBER
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: myproject2-service
spec:
  selector:
    app: myproject2  # Match the label from the deployment
  ports:
    - protocol: TCP
      port: 80           # Expose this port externally
      targetPort: 8082    # Port the container listens on
      nodePort: 30080     # Expose the service on node port 30080
  type: NodePort         # Expose the service via NodePort

