---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject2
  template:
    metadata:
      labels:
        app: myproject2
    spec:
      containers:
      - name: healthcare
        image: deepak377/myproject2:17
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: myproject2-service
spec:
  selector:
    app: myproject2  
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 8082    
      nodePort: 30080     
  type: NodePort       

